# Generated by Django 5.0.1 on 2024-03-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_mymodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
    ]
